"""add neighbors to session

Revision ID: 03f1b580551b
Revises: 0c562f351770
Create Date: 2023-03-28 11:24:03.851526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f1b580551b'
down_revision = '0c562f351770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('neighbors', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('neighbors')

    # ### end Alembic commands ###
