"""gmail attachments

Revision ID: 04d06e6391c1
Revises: 25645b91153a
Create Date: 2023-02-03 20:10:52.361514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d06e6391c1'
down_revision = '25645b91153a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_attachment',
    sa.Column('md5', sa.Text(), nullable=False),
    sa.Column('attachment_id', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('gmail_message_id', sa.String(length=240), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('part_id', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('file_extension', sa.Text(), nullable=True),
    sa.Column('filepath', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['gmail_message_id'], ['gmail_message.id'], name=op.f('fk_gmail_attachment_gmail_message_id_gmail_message')),
    sa.PrimaryKeyConstraint('md5', name=op.f('pk_gmail_attachment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gmail_attachment')
    # ### end Alembic commands ###
