"""platform columns

Revision ID: 0875c658f692
Revises: 575e3e2eee92
Create Date: 2023-04-06 04:50:04.732849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0875c658f692'
down_revision = '575e3e2eee92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_column',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], name=op.f('fk_platform_column_platform_id_platform')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_column')),
    sa.UniqueConstraint('platform_id', 'column_name', name='_unique_constraint_plat_col')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_column')
    # ### end Alembic commands ###
