"""empty message

Revision ID: 0c562f351770
Revises: f31834b8c7a0
Create Date: 2023-03-16 17:04:25.185228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c562f351770'
down_revision = 'f31834b8c7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_boundaries', sa.Text(), nullable=True))
        batch_op.drop_constraint('fk_audio_file_workspace_id_workspace', type_='foreignkey')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_session_workspace_id_workspace'), 'workspace', ['workspace_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_session_workspace_id_workspace'), type_='foreignkey')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('audio_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_audio_file_workspace_id_workspace', 'workspace', ['workspace_id'], ['id'])
        batch_op.drop_column('word_boundaries')

    # ### end Alembic commands ###
