"""add unique constraints

Revision ID: 1ab7d91eefb7
Revises: 8e15ecc0a1e1
Create Date: 2023-02-17 23:01:49.356202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab7d91eefb7'
down_revision = '8e15ecc0a1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_data', schema=None) as batch_op:
        batch_op.create_unique_constraint('_unique_constraint_uc', ['platform_id', 'name'])

    with op.batch_alter_table('platform', schema=None) as batch_op:
        batch_op.create_unique_constraint('_unique_constraint_uc', ['workspace_id', 'name'])

    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_workspace_user_id'), ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_workspace_user_id'), type_='unique')

    with op.batch_alter_table('platform', schema=None) as batch_op:
        batch_op.drop_constraint('_unique_constraint_uc', type_='unique')

    with op.batch_alter_table('auth_data', schema=None) as batch_op:
        batch_op.drop_constraint('_unique_constraint_uc', type_='unique')

    # ### end Alembic commands ###
