"""slack channel

Revision ID: 335c64c2c880
Revises: c202b9c6e721
Create Date: 2023-01-31 12:10:16.534006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335c64c2c880'
down_revision = 'c202b9c6e721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('is_channel', sa.Boolean(), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=True),
    sa.Column('is_im', sa.Boolean(), nullable=True),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('is_general', sa.Boolean(), nullable=True),
    sa.Column('unlinked', sa.Integer(), nullable=True),
    sa.Column('name_normalized', sa.String(length=120), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.Column('is_ext_shared', sa.Boolean(), nullable=True),
    sa.Column('is_org_shared', sa.Boolean(), nullable=True),
    sa.Column('is_pending_ext_shared', sa.Boolean(), nullable=True),
    sa.Column('is_member', sa.Boolean(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('is_mipm', sa.Boolean(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('num_members', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slack_channel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slack_channel_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_slack_channel_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_channel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slack_channel_name'))
        batch_op.drop_index(batch_op.f('ix_slack_channel_channel_id'))

    op.drop_table('slack_channel')
    # ### end Alembic commands ###
