"""empty message

Revision ID: 33e767027787
Revises: 12963b4140f2
Create Date: 2023-02-08 21:05:14.692312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e767027787'
down_revision = '12963b4140f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_text', sa.Text(), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.TEXT(), nullable=True))
        batch_op.drop_column('has_text')

    # ### end Alembic commands ###
