"""slack message

Revision ID: 410f1d49c284
Revises: 335c64c2c880
Create Date: 2023-01-31 12:26:57.863924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410f1d49c284'
down_revision = '335c64c2c880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.String(length=120), nullable=True),
    sa.Column('type', sa.String(length=60), nullable=True),
    sa.Column('user', sa.String(length=20), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slack_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slack_message_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_slack_message_ts'), ['ts'], unique=True)
        batch_op.create_index(batch_op.f('ix_slack_message_user'), ['user'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slack_message_user'))
        batch_op.drop_index(batch_op.f('ix_slack_message_ts'))
        batch_op.drop_index(batch_op.f('ix_slack_message_channel'))

    op.drop_table('slack_message')
    # ### end Alembic commands ###
