"""create audio file table

Revision ID: 48550444996a
Revises: 1ab7d91eefb7
Create Date: 2023-02-18 04:06:04.803021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48550444996a'
down_revision = '1ab7d91eefb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_audio_file_workspace_id_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_file'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_file')
    # ### end Alembic commands ###
