"""setting

Revision ID: 575e3e2eee92
Revises: 9f8266f81ada
Create Date: 2023-04-06 02:18:54.160060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575e3e2eee92'
down_revision = '9f8266f81ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pscore_method', sa.Text(), nullable=True),
    sa.Column('embeddings', sa.Text(), nullable=True),
    sa.Column('num_neighbors', sa.Integer(), nullable=True),
    sa.Column('num_gmail_msg', sa.Integer(), nullable=True),
    sa.Column('num_days_slack', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_setting_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_setting')),
    sa.UniqueConstraint('user_id', name=op.f('uq_setting_user_id'))
    )
    op.drop_table('settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('embeddings', sa.TEXT(), nullable=True),
    sa.Column('num_neighbors', sa.INTEGER(), nullable=True),
    sa.Column('num_gmail_msg', sa.INTEGER(), nullable=True),
    sa.Column('num_days_slack', sa.INTEGER(), nullable=True),
    sa.Column('pscore_method', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_settings_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_settings'),
    sa.UniqueConstraint('user_id', name='uq_settings_user_id')
    )
    op.drop_table('setting')
    # ### end Alembic commands ###
