"""priority list method

Revision ID: 5c5205a1c534
Revises: c0c904258ca9
Create Date: 2023-02-23 19:23:14.603533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c5205a1c534'
down_revision = 'c0c904258ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_to_message_table')
    with op.batch_alter_table('gmail_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Text(), nullable=True))

    with op.batch_alter_table('priority_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('_unique_constraint_sess_plat', ['session_id', 'platform_id'])

    with op.batch_alter_table('priority_list_method', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('_unique_constraint_plat_name', ['platform_id', 'name'])
        batch_op.drop_constraint('fk_priority_list_method_priority_list_id_priority_list', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_priority_list_method_platform_id_platform'), 'platform', ['platform_id'], ['id'])
        batch_op.drop_column('priority_list_id')

    with op.batch_alter_table('slack_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_message', schema=None) as batch_op:
        batch_op.drop_column('session_id')

    with op.batch_alter_table('priority_list_method', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_list_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_priority_list_method_platform_id_platform'), type_='foreignkey')
        batch_op.create_foreign_key('fk_priority_list_method_priority_list_id_priority_list', 'priority_list', ['priority_list_id'], ['id'])
        batch_op.drop_constraint('_unique_constraint_plat_name', type_='unique')
        batch_op.drop_column('platform_id')

    with op.batch_alter_table('priority_list', schema=None) as batch_op:
        batch_op.drop_constraint('_unique_constraint_sess_plat', type_='unique')
        batch_op.drop_column('session_id')

    with op.batch_alter_table('gmail_message', schema=None) as batch_op:
        batch_op.drop_column('session_id')

    op.create_table('platform_to_message_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('platform_id', sa.INTEGER(), nullable=True),
    sa.Column('message_table_name', sa.TEXT(), nullable=True),
    sa.Column('python_path', sa.TEXT(), nullable=True),
    sa.Column('func_name', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], name='fk_platform_to_message_table_platform_id_platform'),
    sa.PrimaryKeyConstraint('id', name='pk_platform_to_message_table'),
    sa.UniqueConstraint('platform_id', name='uq_platform_to_message_table_platform_id')
    )
    # ### end Alembic commands ###
