"""Add model justification.

Revision ID: 7db3b11e9aec
Revises: e2b2c7aa1eb8
Create Date: 2023-03-14 17:33:25.432160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db3b11e9aec'
down_revision = 'e2b2c7aa1eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gmail_attachment', schema=None) as batch_op:
        batch_op.create_unique_constraint('_unique_constraint_gid_md5', ['gmail_message_id', 'md5'])

    with op.batch_alter_table('priority_item_method', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_justification', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('priority_item_method', schema=None) as batch_op:
        batch_op.drop_column('model_justification')

    with op.batch_alter_table('gmail_attachment', schema=None) as batch_op:
        batch_op.drop_constraint('_unique_constraint_gid_md5', type_='unique')

    # ### end Alembic commands ###
