"""add sessions table

Revision ID: 85f337478ffc
Revises: 7db3b11e9aec
Create Date: 2023-03-16 13:32:58.812446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f337478ffc'
down_revision = '7db3b11e9aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_session'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    # ### end Alembic commands ###
