"""add relationship

Revision ID: 884d0c47ef35
Revises: 5aa04c3228a2
Create Date: 2023-02-24 15:25:28.196358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884d0c47ef35'
down_revision = '5aa04c3228a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('test')
    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('test',
    #sa.Column('arr', sa.NUMERIC(), nullable=True)
    #)
    pass
    # ### end Alembic commands ###
