"""settings

Revision ID: 92f0b791403a
Revises: 03f1b580551b
Create Date: 2023-04-06 01:58:59.643689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f0b791403a'
down_revision = '03f1b580551b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('priority_method', sa.Text(), nullable=True),
    sa.Column('embeddings', sa.Text(), nullable=True),
    sa.Column('num_neighbors', sa.Integer(), nullable=True),
    sa.Column('num_gmail_msg', sa.Integer(), nullable=True),
    sa.Column('num_days_slack', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_settings_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_settings_user_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
