"""create workspace, platform and modify primary and foreign keys for users and channels

Revision ID: 939082703ed3
Revises: 33e767027787
Create Date: 2023-02-16 13:34:29.299526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939082703ed3'
down_revision = '33e767027787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_workspace_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace'))
    )
    op.create_table('platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('auth_method', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_platform_workspace_id_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform'))
    )
    op.create_table('auth_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('is_data', sa.Boolean(), nullable=True),
    sa.Column('is_blob', sa.Boolean(), nullable=True),
    sa.Column('is_path', sa.Boolean(), nullable=True),
    sa.Column('file_data', sa.Text(), nullable=True),
    sa.Column('file_blob', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], name=op.f('fk_auth_data_platform_id_platform')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_data'))
    )
    with op.batch_alter_table('gmail_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_gmail_user_platform_id_platform'), 'platform', ['platform_id'], ['id'])

    with op.batch_alter_table('slack_channel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_slack_channel_platform_id_platform'), 'platform', ['platform_id'], ['id'])

    with op.batch_alter_table('slack_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_slack_user_platform_id_platform'), 'platform', ['platform_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_slack_user_platform_id_platform'), type_='foreignkey')
        batch_op.drop_column('platform_id')

    with op.batch_alter_table('slack_channel', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_slack_channel_platform_id_platform'), type_='foreignkey')
        batch_op.drop_column('platform_id')

    with op.batch_alter_table('gmail_user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_gmail_user_platform_id_platform'), type_='foreignkey')
        batch_op.drop_column('platform_id')

    op.drop_table('auth_data')
    op.drop_table('platform')
    op.drop_table('workspace')
    # ### end Alembic commands ###
