"""add unique gmail link

Revision ID: 9f60da0f00dd
Revises: f803ad5ecd52
Create Date: 2023-02-19 03:04:04.060126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f60da0f00dd'
down_revision = 'f803ad5ecd52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gmail_link', schema=None) as batch_op:
        batch_op.create_unique_constraint('_unique_constraint_gl', ['gmail_message_id', 'link'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gmail_link', schema=None) as batch_op:
        batch_op.drop_constraint('_unique_constraint_gl', type_='unique')

    # ### end Alembic commands ###
