"""priority tables

Revision ID: c0c904258ca9
Revises: 6405f1f0b6ba
Create Date: 2023-02-22 16:58:07.796106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c904258ca9'
down_revision = '6405f1f0b6ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priority_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('input_text_value', sa.Text(), nullable=True),
    sa.Column('embedding_vector', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_priority_message'))
    )
    op.create_table('platform_to_message_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('message_table_name', sa.Text(), nullable=True),
    sa.Column('python_path', sa.Text(), nullable=True),
    sa.Column('func_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], name=op.f('fk_platform_to_message_table_platform_id_platform')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_to_message_table')),
    sa.UniqueConstraint('platform_id', name=op.f('uq_platform_to_message_table_platform_id'))
    )
    op.create_table('priority_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.Column('p_a', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], name=op.f('fk_priority_list_platform_id_platform')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_priority_list'))
    )
    op.create_table('priority_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('priority_list_id', sa.Integer(), nullable=True),
    sa.Column('priority_message_id', sa.Integer(), nullable=True),
    sa.Column('p_b', sa.Float(), nullable=True),
    sa.Column('p_b_a', sa.Float(), nullable=True),
    sa.Column('p_a_b', sa.Float(), nullable=True),
    sa.Column('p_a', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['priority_list_id'], ['priority_list.id'], name=op.f('fk_priority_item_priority_list_id_priority_list')),
    sa.ForeignKeyConstraint(['priority_message_id'], ['priority_message.id'], name=op.f('fk_priority_item_priority_message_id_priority_message')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_priority_item'))
    )
    op.create_table('priority_list_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority_list_id', sa.Integer(), nullable=True),
    sa.Column('p_m_a', sa.Float(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('python_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['priority_list_id'], ['priority_list.id'], name=op.f('fk_priority_list_method_priority_list_id_priority_list')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_priority_list_method'))
    )
    op.create_table('priority_item_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority_item_id', sa.Integer(), nullable=True),
    sa.Column('priority_list_method_id', sa.Integer(), nullable=True),
    sa.Column('p_b_m_a', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['priority_item_id'], ['priority_item.id'], name=op.f('fk_priority_item_method_priority_item_id_priority_item')),
    sa.ForeignKeyConstraint(['priority_list_method_id'], ['priority_list_method.id'], name=op.f('fk_priority_item_method_priority_list_method_id_priority_list_method')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_priority_item_method'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('priority_item_method')
    op.drop_table('priority_list_method')
    op.drop_table('priority_item')
    op.drop_table('priority_list')
    op.drop_table('platform_to_message_table')
    op.drop_table('priority_message')
    # ### end Alembic commands ###
