"""slack user

Revision ID: c202b9c6e721
Revises: 8d8d4d93cea2
Create Date: 2023-01-28 16:00:39.521131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c202b9c6e721'
down_revision = '8d8d4d93cea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('team_id', sa.String(length=20), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('real_name', sa.String(length=120), nullable=True),
    sa.Column('tz', sa.String(length=120), nullable=True),
    sa.Column('tz_label', sa.String(length=120), nullable=True),
    sa.Column('tz_offset', sa.Integer(), nullable=True),
    sa.Column('profile_avatar_hash', sa.String(length=120), nullable=True),
    sa.Column('profile_status_text', sa.String(length=120), nullable=True),
    sa.Column('profile_status_emoji', sa.String(length=120), nullable=True),
    sa.Column('profile_real_name', sa.String(length=120), nullable=True),
    sa.Column('profile_display_name', sa.String(length=120), nullable=True),
    sa.Column('profile_real_name_normalized', sa.String(length=120), nullable=True),
    sa.Column('profile_display_name_normalized', sa.String(length=120), nullable=True),
    sa.Column('profile_email', sa.String(length=120), nullable=True),
    sa.Column('profile_image_24', sa.String(length=120), nullable=True),
    sa.Column('profile_image_32', sa.String(length=120), nullable=True),
    sa.Column('profile_image_48', sa.String(length=120), nullable=True),
    sa.Column('profile_image_72', sa.String(length=120), nullable=True),
    sa.Column('profile_image_192', sa.String(length=120), nullable=True),
    sa.Column('profile_image_512', sa.String(length=120), nullable=True),
    sa.Column('profile_team', sa.String(length=20), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('is_primary_owner', sa.Boolean(), nullable=True),
    sa.Column('is_restricted', sa.Boolean(), nullable=True),
    sa.Column('is_ultra_restricted', sa.Boolean(), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=True),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.Column('is_app_user', sa.Boolean(), nullable=True),
    sa.Column('has_2fa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slack_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slack_user_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_slack_user_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_slack_user_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slack_user_user_id'))
        batch_op.drop_index(batch_op.f('ix_slack_user_team_id'))
        batch_op.drop_index(batch_op.f('ix_slack_user_name'))

    op.drop_table('slack_user')
    # ### end Alembic commands ###
