"""empty message

Revision ID: c96bd8c107b0
Revises: 4e61a0c5103a
Create Date: 2023-02-05 21:51:20.842386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96bd8c107b0'
down_revision = '4e61a0c5103a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gmail_attachment', schema=None) as batch_op:
        batch_op.alter_column('gmail_message_id',
               existing_type=sa.VARCHAR(length=240),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gmail_attachment', schema=None) as batch_op:
        batch_op.alter_column('gmail_message_id',
               existing_type=sa.VARCHAR(length=240),
               nullable=True)
    # ### end Alembic commands ###
