"""gmail message and user

Revision ID: ce983d4b9f88
Revises: d07c3c9caa5c
Create Date: 2023-02-01 19:22:38.186061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce983d4b9f88'
down_revision = 'd07c3c9caa5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_user',
    sa.Column('email', sa.String(length=240), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('is_newsletter', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('email', name=op.f('pk_gmail_user'))
    )
    op.create_table('gmail_message',
    sa.Column('id', sa.String(length=240), nullable=False),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('from_string', sa.Text(), nullable=True),
    sa.Column('gmail_user_email', sa.String(length=240), nullable=True),
    sa.Column('mime_version', sa.String(length=10), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('is_multipart', sa.Boolean(), nullable=True),
    sa.Column('multipart_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gmail_user_email'], ['gmail_user.email'], name=op.f('fk_gmail_message_gmail_user_email_gmail_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gmail_message'))
    )
    op.create_table('gmail_message_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=240), nullable=True),
    sa.Column('label', sa.String(length=240), nullable=True),
    sa.ForeignKeyConstraint(['gmail_message_id'], ['gmail_message.id'], name=op.f('fk_gmail_message_label_gmail_message_id_gmail_message')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gmail_message_label'))
    )
    op.create_table('gmail_message_list_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=240), nullable=True),
    sa.Column('list_id', sa.Text(), nullable=True),
    sa.Column('message_id', sa.Text(), nullable=True),
    sa.Column('list_unsubscribe', sa.Text(), nullable=True),
    sa.Column('list_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['gmail_message_id'], ['gmail_message.id'], name=op.f('fk_gmail_message_list_metadata_gmail_message_id_gmail_message')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gmail_message_list_metadata'))
    )
    op.create_table('gmail_message_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=240), nullable=True),
    sa.Column('tag', sa.String(length=240), nullable=True),
    sa.ForeignKeyConstraint(['gmail_message_id'], ['gmail_message.id'], name=op.f('fk_gmail_message_tag_gmail_message_id_gmail_message')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gmail_message_tag'))
    )
    op.create_table('gmail_message_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=240), nullable=True),
    sa.Column('text', sa.UnicodeText(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_multipart', sa.Boolean(), nullable=True),
    sa.Column('is_summary', sa.Boolean(), nullable=True),
    sa.Column('is_snippet', sa.Boolean(), nullable=True),
    sa.Column('multipart_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gmail_message_id'], ['gmail_message.id'], name=op.f('fk_gmail_message_text_gmail_message_id_gmail_message')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gmail_message_text'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gmail_message_text')
    op.drop_table('gmail_message_tag')
    op.drop_table('gmail_message_list_metadata')
    op.drop_table('gmail_message_label')
    op.drop_table('gmail_message')
    op.drop_table('gmail_user')
    # ### end Alembic commands ###
