"""Add unread field to slack messages.

Revision ID: d07c3c9caa5c
Revises: f1f5d97b0285
Create Date: 2023-01-31 20:35:53.663286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07c3c9caa5c'
down_revision = 'f1f5d97b0285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_unread', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_message', schema=None) as batch_op:
        batch_op.drop_column('is_unread')

    # ### end Alembic commands ###
