"""empty message

Revision ID: dbdd6092af53
Revises: 33153c9c95f9
Create Date: 2023-02-06 14:50:41.242136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdd6092af53'
down_revision = '33153c9c95f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_attachment',
    sa.Column('md5', sa.Text(), nullable=False),
    sa.Column('slack_message_ts', sa.String(length=40), nullable=False),
    sa.Column('slack_user_id', sa.String(length=20), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=20), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('filepath', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('mimetype', sa.Text(), nullable=True),
    sa.Column('filetype', sa.Text(), nullable=True),
    sa.Column('pretty_type', sa.Text(), nullable=True),
    sa.Column('user_team', sa.String(length=20), nullable=True),
    sa.Column('editable', sa.Boolean(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=True),
    sa.Column('external_type', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('public_url_shared', sa.Boolean(), nullable=True),
    sa.Column('display_as_bot', sa.Boolean(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('url_private', sa.Text(), nullable=True),
    sa.Column('url_private_download', sa.Text(), nullable=True),
    sa.Column('media_display_type', sa.Text(), nullable=True),
    sa.Column('thumb_pdf', sa.Text(), nullable=True),
    sa.Column('thumb_pdf_w', sa.Integer(), nullable=True),
    sa.Column('thumb_pdf_h', sa.Integer(), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('permalink_public', sa.Text(), nullable=True),
    sa.Column('is_starred', sa.Boolean(), nullable=True),
    sa.Column('has_rich_preview', sa.Boolean(), nullable=True),
    sa.Column('file_access', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['slack_message_ts'], ['slack_message.ts'], name=op.f('fk_slack_attachment_slack_message_ts_slack_message')),
    sa.ForeignKeyConstraint(['slack_user_id'], ['slack_user.id'], name=op.f('fk_slack_attachment_slack_user_id_slack_user')),
    sa.PrimaryKeyConstraint('md5', 'slack_message_ts', name=op.f('pk_slack_attachment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_attachment')
    # ### end Alembic commands ###
