"""set up foreign keys

Revision ID: f1f5d97b0285
Revises: 410f1d49c284
Create Date: 2023-01-31 14:06:39.073317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f5d97b0285'
down_revision = '410f1d49c284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_channel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator', sa.String(length=20), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_index('ix_slack_channel_channel_id')
        batch_op.create_index(batch_op.f('ix_slack_channel_creator'), ['creator'], unique=False)
        batch_op.drop_column('channel_id')

    with op.batch_alter_table('slack_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_user_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('slack_channel_id', sa.String(length=20), nullable=True))
        batch_op.alter_column('ts',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=40),
               nullable=False)
        batch_op.drop_index('ix_slack_message_channel')
        batch_op.drop_index('ix_slack_message_ts')
        batch_op.drop_index('ix_slack_message_user')
        batch_op.create_foreign_key(batch_op.f('fk_slack_message_slack_channel_id_slack_channel'), 'slack_channel', ['slack_channel_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_slack_message_slack_user_id_slack_user'), 'slack_user', ['slack_user_id'], ['id'])
        batch_op.drop_column('channel')
        batch_op.drop_column('user')
        batch_op.drop_column('id')

    with op.batch_alter_table('slack_user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_index('ix_slack_user_user_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=20), nullable=True))
        batch_op.create_index('ix_slack_user_user_id', ['user_id'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('slack_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('user', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('channel', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_slack_message_slack_user_id_slack_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_slack_message_slack_channel_id_slack_channel'), type_='foreignkey')
        batch_op.create_index('ix_slack_message_user', ['user'], unique=False)
        batch_op.create_index('ix_slack_message_ts', ['ts'], unique=False)
        batch_op.create_index('ix_slack_message_channel', ['channel'], unique=False)
        batch_op.alter_column('ts',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('slack_channel_id')
        batch_op.drop_column('slack_user_id')

    with op.batch_alter_table('slack_channel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('ix_slack_channel_creator'))
        batch_op.create_index('ix_slack_channel_channel_id', ['channel_id'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('creator')

    # ### end Alembic commands ###
