"""add session id to audio

Revision ID: f31834b8c7a0
Revises: 85f337478ffc
Create Date: 2023-03-16 16:02:53.552593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31834b8c7a0'
down_revision = '85f337478ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_file', schema=None) as batch_op:
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
