"""change audio column name

Revision ID: f6a4b8423ea0
Revises: 48550444996a
Create Date: 2023-02-18 04:10:25.037660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a4b8423ea0'
down_revision = '48550444996a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.Text(), nullable=True))
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.TEXT(), nullable=True))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
