"""add unique slack link

Revision ID: f803ad5ecd52
Revises: 0476a1e3616b
Create Date: 2023-02-19 02:50:01.939374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f803ad5ecd52'
down_revision = '0476a1e3616b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_link', schema=None) as batch_op:
        batch_op.create_unique_constraint('_unique_constraint_su', ['slack_message_ts', 'url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_link', schema=None) as batch_op:
        batch_op.drop_constraint('_unique_constraint_su', type_='unique')

    # ### end Alembic commands ###
